version: '3.8'

services:
  api:
    build: .
    container_name: "scoping-ai-api"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - "8080:8080"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
