version: '3'

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -v -o bin/app cmd/server/main.go
  
  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - docker-compose up --build

  deploy:
    cmds:
      - docker build --build-arg PROJECT_ID=admu-iscs-30-23 -t scoping-ai:latest .
      - docker tag scoping-ai:latest gcr.io/admu-iscs-30-23/scoping-ai:latest
      - docker push gcr.io/admu-iscs-30-23/scoping-ai:latest
      - gcloud run deploy genai-api --image gcr.io/admu-iscs-30-23/scoping-ai:latest --project admu-iscs-30-23  --port 8080 --service-account backendapi@admu-iscs-30-23.iam.gserviceaccount.com --region asia-southeast1 --allow-unauthenticated
